package main

import (
	"log"
	"os"

	"expense-tracker/internal/config"
	"expense-tracker/internal/middleware"
	"expense-tracker/internal/routes"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// swagger docs (placeholder import, to be generated by swag init)
	// _ "expense-tracker/docs"
)

// @title Expense Tracker API
// @version 1.0
// @description Distributed Expense Tracker API with Golang, Gin and PostgreSQL.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@expensetracker.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, relying on environment variables")
	}

	// Connect to Database
	config.ConnectDB()

	// Setup Gin router
	router := gin.Default()

	// CORS Middleware
	router.Use(cors.Default())

	// Rate Limiting Middleware
	router.Use(middleware.RateLimitMiddleware())

	// Setup Routes
	routes.SetupRoutes(router)

	// Swagger Route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on port %s", port)
	router.Run(":" + port)
}
